name: Next-Movie-Viewer CI
run-name: "PR :: ${{ github.head_ref }} -> ${{ github.base_ref}} by ${{github.actor}}"
on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # 1. 레포지토리 checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Node.js 설정
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts"

      # 3. 의존성 설치
      - name: Install dependencies
        run: npm ci

      # 4. Lint 검사
      - name: Run Lint
        run: npm run lint

      # 5. 테스트 실행
      - name: Run Tests
        run: npm run test

      # 6. 빌드 테스트
      - name: Build
        run: npm run build
